---
title: "Territories"
output: html_notebook
---
```{r setup}
# load libraries
library(tidyverse)
library(sf)

# load functions
source("~/db-connections.R")

# connect to databases
leyte <- read_db("Leyte")

# load data
fish_db <- leyte %>% 
  tbl("clownfish") %>% 
  collect()

anem_db <- leyte %>% 
  tbl("anemones") %>% 
  collect() 

dive_db <- leyte %>% 
  tbl("diveinfo") %>% 
  collect()

# read in data generated by anemone_locations.Rmd in the clownfish demographics package
# the point average through the years for each anem_obs
anem_obs_locs <- read_csv("https://raw.githubusercontent.com/pinskylab/clownfish-demographics/master/data/anem_obs_locations.csv?token=AG664YPBYND45ZH7XITOOTC5ROJJC")

# read in data generated by the genomics project, in the protocols folder, scripts 5-7 (remove-regenos through recaptured fish).  The fish_indiv column connects all observations of a fish.
fish_indiv <- read_csv("https://raw.githubusercontent.com/pinskylab/genomics/master/data/fish-obs.csv", col_types = cols(.default = col_character())) 

```

## 1. What anemones do fish visit?
Only searching for fish we have recaptured
```{r}
fish_anem <- fish_db %>% 
  
  # select columns
  select(fish_table_id, anem_table_id, sample_id, tag_id, size, color, sex) %>% 
  
  # connect to fish_indiv
  left_join(mutate(fish_indiv, fish_table_id = as.numeric(fish_table_id)), by = c("fish_table_id", "sample_id", "tag_id")) %>% 
  
  # remove fish without an identity
  filter(!is.na(fish_indiv))%>% 

  
  # join to anemone observations
  left_join(select(anem_db, anem_table_id, dive_table_id, anem_id, anem_obs), by = "anem_table_id") %>% 
  
  # join to diveinfo for date and site info
  left_join(select(dive_db, dive_table_id, date, site), by = "dive_table_id") %>% 
  
  # remove rows without an anem_id
  filter(!is.na(anem_id)) %>% 
  
  
  # add anem_obs locations
  left_join(anem_obs_locs, by = "anem_obs") %>% 
  rename(anem_obs_lat = lat, 
         anem_obs_lon = lon) %>% 
  
  # consolidate the columns into one location
  mutate(lat = ifelse(is.na(anem_obs_lat), anem_id_lat, anem_obs_lat), 
         lon = ifelse(is.na(anem_obs_lon), anem_id_lon, anem_obs_lon)) %>% 
  
  # deselect columns
  select(-contains("anem_obs_l"), 
         -contains("anem_id_l"))

```

# What is the area occupied by each fish that has been captured more than once
```{r}
temp <- fish_anem %>% 
  group_by(fish_indiv) %>% 
  filter(n() > 1)

recaps <- unique(temp$fish_indiv)

area_results <- tibble() 

for (i in seq_along(recaps)){
  x <- filter(fish_anem, fish_indiv == recaps[i])
  
  # create a table of locations
  df <- tibble(lon = x$lon, lat = x$lat)
  
  # close the polygon by adding the first line again
  df <- rbind(df, df[1, ])
  
  poly <- st_sf(st_sfc(st_polygon(list(as.matrix(df)))), crs = 4326)


  y <- tibble(fish_indiv = x$fish_indiv[1], home_range = st_area(poly), site = x$site)
  
  # remove the units from the home_range
  y$home_range <- unclass(y$home_range)
  
  
  area_results <- bind_rows(area_results, y) %>% 
    # distinct(fish_indiv, site, .keep_all = T) %>% 
    arrange(desc(home_range)) %>% 
    distinct()
  
  
}

(base::summary(area_results))
```
# There are some extreme outliers in this data set.  

Fish_indiv 1665 has tag_id 982000411818464 and was seen on 4 different anemones in Wangag.  
```{r}
# everything looks ok, all in the same site.
fish1 <- fish_anem %>% 
  filter(fish_indiv == 1665)

 # create a table of locations
  locs <- tibble(lon = fish1$lon, lat = fish1$lat)
  
  # close the polygon by adding the first line again
  locs <- rbind(locs, locs[1, ])
  
  poly <- st_sf(st_sfc(st_polygon(list(as.matrix(locs)))), crs = 4326)
  
  territory <- tibble(home_range = st_area(poly))
  
# what about observations of the anemone that is farther away?
  anem_1 <- anem_db %>% 
    filter(anem_id == 2560)

```

